### ISSUE TITLE
Broken in python 3.10

### ISSUE THREAD

**Issue by mlmatlock** [cdberkstresser/fah-control#22]
Arch just updated to python 3.10.  Rebuilt FAHC to 3.10, with the following error:

```
$ python /usr/bin/FAHControl
Traceback (most recent call last):
  File "/usr/bin/FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
  File "/usr/lib/python3.10/site-packages/fah/__init__.py", line 25, in <module>
    from . import util
  File "/usr/lib/python3.10/site-packages/fah/util/__init__.py", line 24, in <module>
    from .OrderedDict import *
  File "/usr/lib/python3.10/site-packages/fah/util/OrderedDict.py", line 23, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
No problems were noted on python 3.9.

**Comment by ajgringo619** [comment]
There's a temporary fix on the AUR package page: https://aur.archlinux.org/packages/fahcontrol-gtk3-git; tested and working for me.

**Comment by gardenappl** [comment]
Seeing as there was no response to this in 26 days, I applied that patch to the AUR package myself

**Comment by cdberkstresser** [comment]
merged
